version: '3.4'

services:
  uinversity:
    image: ${DOCKER_REGISTRY-}uinversity
    build:
      context: .
      dockerfile: Uinversity/Dockerfile
    ports: 
    - "127.0.0.1:5041:80"
    depends_on:
      - cache
    links:
      - cache

  cache:
    container_name: redis
    image: redis