version: '3.4'

services:
  cache:
    container_name: redis
    image: redis
  
  database:
    container_name: database
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment: 
      - "MSSQL_SA_PASSWORD=Pa@@w0rd2019"
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
    ports:
      - "5434:1433"

  uinversity:
    image: ${DOCKER_REGISTRY-}uinversity
    build:
      context: .
      dockerfile: Uinversity/Dockerfile
    ports: 
    - "5000:80"
    depends_on:
      - cache
      - database
    links:
      - cache
      - database
    environment:
      - "SqlOptions__ConnectionString=Server=database,1433;Database=University;User Id=sa;Password=Pa@@w0rd2019; encrypt=False;"
    